export const users = [
  {
    email: 'Newell.Paucek@hotmail.com',
    fullName: 'Richard Hickle',
    phone: '1-268-774-3381',
    verificationStatus: false,
    createdAt: 'America/Argentina/Cordoba',
    id: '1',
  },
  {
    email: 'Marlin.Cassin@gmail.com',
    fullName: 'Charlene Bednar',
    phone: '1-423-949-5528 x933',
    verificationStatus: false,
    createdAt: 'America/Los_Angeles',
    id: '2',
  },
  {
    email: 'Aracely.Murray@yahoo.com',
    fullName: 'Renee MacGyver',
    phone: '995.773.0571 x952',
    verificationStatus: false,
    createdAt: 'America/Halifax',
    id: '3',
  },
  {
    email: 'Barry89@yahoo.com',
    fullName: 'Mr. Willard Nienow',
    phone: '(599) 417-3975 x67943',
    verificationStatus: true,
    createdAt: 'Asia/Ashgabat',
    id: '4',
  },
  {
    email: 'Einar_Paucek25@gmail.com',
    fullName: 'Conrad Erdman',
    phone: '359-598-0843 x09342',
    verificationStatus: false,
    createdAt: 'Africa/Tunis',
    id: '5',
  },
  {
    email: 'Eldon_Jacobi5@hotmail.com',
    fullName: 'Bradley Buckridge',
    phone: '351-779-3435',
    verificationStatus: true,
    createdAt: 'America/Thule',
    id: '6',
  },
  {
    email: 'Emery.Rolfson@yahoo.com',
    fullName: 'Christina Smitham-Hyatt',
    phone: '1-935-678-4869 x91257',
    verificationStatus: true,
    createdAt: 'Pacific/Fiji',
    id: '7',
  },
  {
    email: 'Lorenzo.Jast91@hotmail.com',
    fullName: 'Anna Jaskolski',
    phone: '314.606.5916',
    verificationStatus: false,
    createdAt: 'Asia/Ust-Nera',
    id: '8',
  },
  {
    email: 'Werner20@gmail.com',
    fullName: 'Cynthia Boyle',
    phone: '855-733-3775 x7898',
    verificationStatus: true,
    createdAt: 'Arctic/Longyearbyen',
    id: '9',
  },
  {
    email: 'Marshall59@hotmail.com',
    fullName: 'Danny Will',
    phone: '489-900-1039 x473',
    verificationStatus: false,
    createdAt: 'Antarctica/Macquarie',
    id: '10',
  },
  {
    email: 'Gia_Lakin92@gmail.com',
    fullName: 'Ginger Schultz',
    phone: '(731) 626-1484 x8967',
    verificationStatus: true,
    createdAt: 'Atlantic/Bermuda',
    id: '11',
  },
  {
    email: 'Reginald.Maggio@yahoo.com',
    fullName: 'Joann Zieme',
    phone: '944.546.1860 x71427',
    verificationStatus: false,
    createdAt: 'Pacific/Wallis',
    id: '12',
  },
  {
    email: 'Gilda_Welch13@yahoo.com',
    fullName: 'Amelia Johns',
    phone: '1-651-303-8925 x2905',
    verificationStatus: true,
    createdAt: 'Europe/Astrakhan',
    id: '13',
  },
  {
    email: 'Clovis.Zulauf40@yahoo.com',
    fullName: 'Aaron Tillman',
    phone: '893.882.0125',
    verificationStatus: true,
    createdAt: 'America/Montevideo',
    id: '14',
  },
  {
    email: 'Marie_Sipes15@yahoo.com',
    fullName: 'Allan Carter',
    phone: '(200) 975-5751 x3112',
    verificationStatus: true,
    createdAt: 'Indian/Mayotte',
    id: '15',
  },
  {
    email: 'Easton21@hotmail.com',
    fullName: 'Julie Huel',
    phone: '658.482.5654 x1772',
    verificationStatus: false,
    createdAt: 'America/Vancouver',
    id: '16',
  },
  {
    email: 'Holly.Hirthe52@gmail.com',
    fullName: 'Eva Hilll',
    phone: '404.851.8571 x5894',
    verificationStatus: true,
    createdAt: 'Asia/Jerusalem',
    id: '17',
  },
  {
    email: 'Clint.Kemmer44@hotmail.com',
    fullName: 'Roosevelt Ledner',
    phone: '661-501-7228',
    verificationStatus: true,
    createdAt: 'Africa/Djibouti',
    id: '18',
  },
  {
    email: 'Dawson.Schamberger5@hotmail.com',
    fullName: 'Charlie Kiehn',
    phone: '572.772.1479 x7969',
    verificationStatus: true,
    createdAt: 'America/Nuuk',
    id: '19',
  },
  {
    email: 'Shirley.Schimmel17@yahoo.com',
    fullName: 'Miss Melody Krajcik',
    phone: '955.427.7276 x69673',
    verificationStatus: false,
    createdAt: 'Asia/Yakutsk',
    id: '20',
  },
  {
    email: 'Rowland.Huels@hotmail.com',
    fullName: 'Norman Durgan',
    phone: '1-789-380-7638 x82160',
    verificationStatus: false,
    createdAt: 'Pacific/Kosrae',
    id: '21',
  },
  {
    email: 'Ron.Schneider50@hotmail.com',
    fullName: 'Marlon Kirlin',
    phone: '(686) 870-8245 x81249',
    verificationStatus: true,
    createdAt: 'America/Recife',
    id: '22',
  },
  {
    email: 'Lemuel_Johnston29@hotmail.com',
    fullName: 'Dr. Bradford Deckow',
    phone: '1-860-559-6089 x921',
    verificationStatus: false,
    createdAt: 'Pacific/Gambier',
    id: '23',
  },
  {
    email: 'Mable.Ruecker25@yahoo.com',
    fullName: 'Laurence Brown III',
    phone: '390.339.7006 x50708',
    verificationStatus: false,
    createdAt: 'America/Guayaquil',
    id: '24',
  },
  {
    email: 'Keshawn_Murazik@gmail.com',
    fullName: 'Martha Beatty',
    phone: '449-944-4945',
    verificationStatus: false,
    createdAt: 'Africa/Bujumbura',
    id: '25',
  },
  {
    email: 'Hilario52@yahoo.com',
    fullName: 'Ron Mueller',
    phone: '(800) 614-3642 x255',
    verificationStatus: true,
    createdAt: 'America/Dawson',
    id: '26',
  },
  {
    email: 'Juanita.Prohaska90@hotmail.com',
    fullName: 'Delores Hyatt',
    phone: '992-506-9215 x55752',
    verificationStatus: false,
    createdAt: 'Indian/Mayotte',
    id: '27',
  },
  {
    email: 'Jeffry.Kessler@gmail.com',
    fullName: 'Shannon Schuppe',
    phone: '1-323-798-0338 x883',
    verificationStatus: false,
    createdAt: 'Europe/Paris',
    id: '28',
  },
  {
    email: 'Jamir.Mayert@hotmail.com',
    fullName: 'Winston Reichert',
    phone: '1-865-664-5289 x269',
    verificationStatus: true,
    createdAt: 'Indian/Kerguelen',
    id: '29',
  },
  {
    email: 'Ila.Jaskolski@yahoo.com',
    fullName: 'Karl Streich',
    phone: '(675) 729-5713 x74105',
    verificationStatus: false,
    createdAt: 'Europe/Gibraltar',
    id: '30',
  },
  {
    email: 'Haylee98@gmail.com',
    fullName: 'Kayla Schamberger',
    phone: '1-238-834-1129 x873',
    verificationStatus: true,
    createdAt: 'America/Anguilla',
    id: '31',
  },
  {
    email: 'Carlotta15@gmail.com',
    fullName: 'Mandy Connelly',
    phone: '(446) 875-4144 x8137',
    verificationStatus: true,
    createdAt: 'America/Indiana/Vevay',
    id: '32',
  },
  {
    email: 'Nelle.Gorczany48@yahoo.com',
    fullName: 'Dr. Mandy Armstrong',
    phone: '1-746-353-6674',
    verificationStatus: true,
    createdAt: 'Asia/Phnom_Penh',
    id: '33',
  },
  {
    email: 'Erling4@yahoo.com',
    fullName: 'Erika Jaskolski',
    phone: '(335) 219-2070 x969',
    verificationStatus: true,
    createdAt: 'Asia/Hong_Kong',
    id: '34',
  },
  {
    email: 'Wilma.Thompson2@hotmail.com',
    fullName: 'Mr. Dwayne Bruen-Hodkiewicz',
    phone: '(549) 605-6018 x6695',
    verificationStatus: false,
    createdAt: 'Antarctica/Troll',
    id: '35',
  },
  {
    email: 'Rosemarie_Herzog7@gmail.com',
    fullName: 'Dustin Lockman',
    phone: '785.500.7263 x9230',
    verificationStatus: true,
    createdAt: 'America/Cuiaba',
    id: '36',
  },
  {
    email: 'Javonte_Spencer-Feest12@yahoo.com',
    fullName: 'Alan Willms',
    phone: '1-435-669-4540',
    verificationStatus: true,
    createdAt: 'Pacific/Auckland',
    id: '37',
  },
];
