global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://google.com
          - http://localhost:8000  
    relabel_configs:
      - source_labels: [__param_target]
        target_label: target
      - target_label: __param_module
        replacement: http_2xx
      - target_label: job
        replacement: blackbox

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:8080']
